task: "mmmu_pro_standard_mimo_zs"
dataset_path: MMMU/MMMU_Pro
dataset_name: "standard (10 options)"
test_split: test
output_type: generate_until
doc_to_visual: !function mimo_utils.mmmu_pro_doc_to_visual
doc_to_text: !function mimo_utils.mmmu_pro_doc_to_text
doc_to_target: "{{answer}}"
generation_kwargs:
  max_new_tokens: 32768
  temperature: 0.0
  do_sample: false
process_results: !function mimo_utils.mmmu_pro_process_results

filter_list:
  - name: "flexible-extract"
    filter:
      - function: !function mimo_utils.BoxedFilter

metric_list:
  - metric: mmmu_acc
    aggregation: !function mimo_utils.mmmu_pro_aggregate_results
    higher_is_better: true

metadata:
  version: 0.0
  interleaved_format: false

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "Put your final answer in \\boxed{}."
