group: screenspot_point_in_box
task: screenspot_point_in_box_reasoning
include: _default_template_point_yaml
test_split: test
process_docs: !function utils_point.screenspot_point_process_docs_abs
doc_to_text: !function utils_point.screenspot_point_doc_to_text_abs
generation_kwargs:
  until:
    - "ASSISTANT:"
  max_new_tokens: 16384
  temperature: 0.6
  do_sample: True

lmms_eval_specific_kwargs:
  default:
    pre_prompt: "Provide the point for the command:"
    post_prompt: ' Output the point in a JSON array format: [{"point_2d": [x, y]}].'
