defaults:
  - gspo_llmjudge_shared
  - _self_

hydra:
  searchpath:
    - file://${oc.env:REPO_ROOT}/verl/trainer/config

data:
  max_pixels: 16777216  # 4096 x 4096
  max_prompt_length: 18432
  max_response_length: 18432
  filter_overlong_prompts: true
  normalize_bbox_to_1000: true

actor_rollout_ref:
  model:
    path: "Qwen/Qwen3-VL-8B-Instruct"
  actor:
    ppo_max_token_len_per_gpu: 36864  # 18432 + 18432
  rollout:
    max_num_batched_tokens: 36864
    log_prob_max_token_len_per_gpu: 36864
  ref:
    log_prob_max_token_len_per_gpu: 36864

critic:
  ppo_max_token_len_per_gpu: 36864
  forward_max_token_len_per_gpu: 36864

reward_model:
  forward_max_token_len_per_gpu: 36864
