dataset_path: AI4Math/MathVista
dataset_kwargs:
  token: True
task: "mathvista_testmini_mimo_zs"
test_split: testmini
output_type: generate_until
doc_to_visual: !function mimo_utils.mathvista_doc_to_visual
doc_to_text: !function mimo_utils.mimo_mathvista_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 32768
  temperature: 0
  top_p: 1.0
  do_sample: false
process_results: !function mimo_utils.mathvista_process_results
metric_list:
  - metric: submission
    aggregation: !function mimo_utils.mathvista_aggregate_results
    higher_is_better: true
